name-template: 'gazelle-quick-craft.user.js v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '* $TITLE by @$AUTHOR in (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed

  $CHANGES
footer: |
  
  **Full Changelog**: $REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
include-paths:
  - dist/gazelle-quick-craft.user.js
